### ISSUE TITLE
bug: Cannot read properties of undefined (reading 'getText')

### ISSUE THREAD

**Issue by brodenbrett** [ionic-team/ionic-angular-standalone-codemods#31]
### Prerequisites

- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-angular-standalone-codemods) that already report this problem, without success.

### Codemod version

0.0.7

### Current Behavior

An error occurs when running the utility:

```
┌  Ionic Angular Standalone Codemods
┌  This utility will migrate your Ionic Angular project to use the new standalone components from Ionic Framework v7.5.0.
│
▲  --------------------------------------------------
│
▲  ⚠️  This utility is experimental. Always review the changes made before committing them to your project. ⚠️
│
▲  For manual migration, see the guide at: https://www.ionicframework.com/docs/angular/build-options#migrating-from-modules-to-standalone
│
▲  --------------------------------------------------
│
◇  Would you like to run this migration as a dry run? No changes will be written to your project.
│  Yes
│
◇  Please enter the path to your project (default is the current working directory):
│  /Users/<myusername>/Apps/<projectfolder>
│
■  An error occurred during the migration.
│
■  Cannot read properties of undefined (reading 'getText')
│
└  If you encounter any issues with this migration utility, please report them at: https://github.com/ionic-team/ionic-angular-standalone-codemods/issues
```

### Expected Behavior

The utility should run.

### Steps to Reproduce

1. `npx @ionic/angular-standalone-codemods` in terminal at the package folder
2. Hit 'Yes'
3. Use current directory

### Additional Information

Ionic Version: 7.5.6
Angular Version: 17.0.4
Typescript Version: 5.2.2
Node Version: 20.10.0

**Comment by pqnet** [comment]
I have the same issue. Is there a way to print some debug information?

**Comment by brodenbrett** [comment]
@pqnet I'm on a time crunch so I ended up going doing the conversion manually. It wasn't difficult, just a bit gruelling - it can take a while depending on the complexity of your app. 

If you're in the same situation [here's the steps I followed](https://ionicframework.com/docs/angular/build-options#standalone-based-applications). I recommend creating a backup of your repository first.

**Comment by pqnet** [comment]
I had a look at the script through a debugger, and I think this is an issue that comes when importing `IonModule` in secondary modules without the `.forRoot` part. I believe the scripts looks for that member call to identify which modules have to be updated.

**Comment by DmitrySharabin** [comment]
I'm facing the same issue. 😭

**Comment by pqnet** [comment]
This repository exhibits the odd behavior. The commits list the sequence of operations that were done to generate that repository.

https://github.com/pqnet/ionic-test-migration
