### ISSUE TITLE
bug: Expected the module specifier to be a string literal.

### ISSUE THREAD

**Issue by luke-rogers** [ionic-team/ionic-angular-standalone-codemods#32]
### Prerequisites

- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-angular-standalone-codemods) that already report this problem, without success.

### Codemod version

0.0.7

### Current Behavior

Run the codemod against my project and it fails half way through with the error `Expected the module specifier to be a string literal.`

### Expected Behavior

The codemod successfully runs without error.

If the codemod does error, it should attempt to print the source file path that cause the error so the user can attempt to manually resolve the issue and run the codemod again.

### Steps to Reproduce

1. Run codemod against my project

**Comment by saschwarz** [comment]
It would also be helpful if the file/line number of the offending module specifier was output to stderr.
