### ISSUE TITLE
bug: Ionic 8 doesn't work with this cli

### ISSUE THREAD

**Issue by qwe12e** [ionic-team/ionic-angular-standalone-codemods#45]
### Prerequisites

- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-angular-standalone-codemods) that already report this problem, without success.

### Codemod version

0.3.0

### Current Behavior

I'm trying to use this migration tool to use standalone component. I recently upgraded my app version to `"@ionic/angular": "^8.0.0",` but when I look at this cli code I can see that you guys looking at 
if major < 7
if minor < 5

and of course in the new version we have a minor version of 0 so we can't continue

### Expected Behavior

cli should work with ionic 8

### Steps to Reproduce

1. create an ionic angular app with ionic 8
2. run `npx @ionic/angular-standalone-codemods`

**Comment by FurbyX92** [comment]
if (majorVersion < 7) {
      logVersionError();
      return false;
    }
    // only need to add if is major v7 then compare with minor 5.
    if (majorVersion == 7 && minorVersion < 5) {
      logVersionError();
      return false;
    }
